services:
  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    command: keydb-server /etc/keydb/keydb.conf --server-threads 4 --requirepass password --appendonly yes
    volumes:
      - ./volumes/keydb/:/data/
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  gibbon-replay-server:
    build: ../gibbon-replay-server/
    ports:
      - 5173:3000
    environment:
      REDIS_HOST: keydb
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      AUTH_USER: admin
      AUTH_PASSWORD: password

  demosite:
    build: ../demosite/
    ports:
      - 5174:3000
    environment:
      GIBBON_REPLAY_URL: http://localhost:5173
